### ISSUE TITLE
(x64 Debian) Web Server Misconfiguration 

### ISSUE THREAD

**Issue by mslsystems** [Forceu/partkeepr_docker#7]
Hey,

i'm trying to install your Partkeepr image an my x64 Debian with docker.

I was doing all the steps incl. creating the folder and chown to www-data.

Im trying to do the setup with Firefox 100.

But when Partkeepr is testing the webserver configuration, it says: Web Server Misconfiguration. 

![partkeepr_error](https://user-images.githubusercontent.com/104095299/169688986-1280af25-c875-4975-8ebb-28aed49d956a.PNG)

What am I doing wrong?

**Comment by Forceu** [comment]
Sorry for the late reply, I only just saw this issue. Do you have any output from your docker container?

**Comment by spamik** [comment]
Same here, in container log appear this:

```
127.0.0.1 -  03/Nov/2022:15:29:12 +0000 "POST /setup/tests/check-php.php" 200
127.0.0.1 -  03/Nov/2022:15:29:12 +0000 "POST /setup/tests/check-php-prerequisites.php" 200
[03-Nov-2022 15:29:12] WARNING: [pool www] child 16 said into stderr: "NOTICE: PHP message: PHP Notice:  A non well formed numeric value encountered in /app/app/PartKeeprRequirements.php on line 126"
127.0.0.1 -  03/Nov/2022:15:29:12 +0000 "POST /setup/tests/check.php" 200
127.0.0.1 -  03/Nov/2022:15:29:12 +0000 "POST /setup.php" 500
[03-Nov-2022 15:29:12] WARNING: [pool www] child 15 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: The file "/app/app/config/config_setup.yml" does not exist. in /app/vendor/symfony/symfony/src/Symfony/Component/Config/FileLocator.php:42"
[03-Nov-2022 15:29:12] WARNING: [pool www] child 15 said into stderr: "Stack trace:"
[03-Nov-2022 15:29:12] WARNING: [pool www] child 15 said into stderr: "#0 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Config/FileLocator.php(52): Symfony\Component\Config\FileLocator->locate('/app/app/config...', NULL, true)"
[03-Nov-2022 15:29:12] WARNING: [pool www] child 15 said into stderr: "#1 /app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(42): Symfony\Component\HttpKernel\Config\FileLocator->locate('/app/app/config...')"
[03-Nov-2022 15:29:12] WARNING: [pool www] child 15 said into stderr: "#2 /app/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/app/app/config...', NULL)"
[03-Nov-2022 15:29:12] WARNING: [pool www] child 15 said into stderr: "#3 /app/app/SetupAppKernel.php(38): Symfony\Component\Config\Loader\DelegatingLoader->load('/app/app/config...')"
[03-Nov-2022 15:29:12] WARNING: [pool www] child 15 said into stderr: "#4 /app/app/bootstrap.php.cache(2817): SetupAppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader..."
```

**Comment by st12q** [comment]
Same
